---
- name: Setup Borg Backup
  include_role:
    name: borgbase.ansible_role_borgbackup
  vars:
    borg_encryption_passphrase: TOKEN
    borg_install_method: package
    borgmatic_timer_hour: 13
    borgmatic_timer_minute: 0
    borg_repository:
      - URL
    borg_source_directories:
      - /etc/grafana/grafana.ini
      - /var/lib/grafana/grafana.db

...