---

- name: Setup cAdvisor
  community.docker.docker_container:
    name: cadvisor
    image: "gcr.io/cadvisor/cadvisor:v0.52.1"
    state: started
    restart_policy: "unless-stopped"
    recreate: true
    command: "--docker_only=true"
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

...