---
- name: Install Cockpit
  ansible.builtin.dnf:
    name: cockpit
    state: present

- name: Enable cockpit service
  ansible.builtin.systemd:
    name: cockpit.socket
    state: started
    enabled: true

- name: Open cockpit port on firewall
  ansible.posix.firewalld:
    service: cockpit
    permanent: true
    zone: public
    state: enabled
    immediate: true

- name: Install vagrant
  ansible.builtin.dnf:
    name: yum-utils
    state: present

...