---
- name: Install Cockpit
  ansible.builtin.dnf:
    name: cockpit
    state: present

- name: Install cockpit navigator plugin
  ansible.builtin.dnf:
    name: https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/c/cockpit-navigator-0.5.9-2.el9.noarch.rpm
    state: present

- name: Enable cockpit service
  ansible.builtin.systemd:
    name: cockpit.socket
    state: started
    enabled: true

- name: Open cockpit port on firewall
  ansible.posix.firewalld:
    service: cockpit
    permanent: true
    zone: public
    state: enabled
    immediate: true

- name: Install vagrant
  ansible.builtin.dnf:
    name: yum-utils
    state: present

...