---
- name: Create frigate config dir
  ansible.builtin.file:
    path: /media/Frigate/config/
    state: directory
    mode: '0755'

- name: Copy camera configuration file
  ansible.builtin.template:
    src: "frigate/config.yml"
    dest: "/media/Frigate/config/config.yml"

- name: Pull and run Frigate
  community.docker.docker_container:
    name: frigate
    image: "ghcr.io/blakeblackshear/frigate:0.15.0"
    state: started
    restart_policy: "unless-stopped"
    privileged: true
    mounts:
      - type: tmpfs
        target: /tmp/cache
        tmpfs_size: "1GB"
    shm_size: "128M"
    memory: "3G"
    cpus: 1.0
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/Frigate/config:/config
      - /media/Frigate/storage:/media/frigate
    recreate: true
    env:
      FRIGATE_RTSP_PASSWORD: '{{ frigate_rtsp_password }}'
      LIBVA_DRIVER_NAME: radeonsi
    ports:
      - 5001:5000
      - 8554:8554
      - 8555:8555/tcp
      - 8555:8555/udp

...