---
- name: Create Ghost directories
  ansible.builtin.file:
    path: /mnt/media/Ghost
    state: directory
    mode: '0755'
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'

- name: Create db.env file
  ansible.builtin.copy:
    dest: /mnt/media/Ghost/db.env
    content: |
      MYSQL_ROOT_PASSWORD={{ ghost_mysql_root_password }}

- name: Create app.env file
  ansible.builtin.copy:
    dest: /mnt/media/Ghost/app.env
    content: |
      url={{ ghost_url }}
      database__client={{ ghost_database_client }}
      database__connection__host={{ ghost_database_connection_host }}
      database__connection__user={{ ghost_database_connection_user }}
      database__connection__password={{ ghost_database_connection_password }}
      database__connection__database={{ ghost_database_connection_database }}

- name: Copy Docker-compose file
  become: false
  ansible.builtin.copy:
    src: files/ghost/docker-compose.yml
    dest: /mnt/media/Ghost

- name: Run Ghost
  community.docker.docker_compose_v2:
    project_src: /mnt/media/Ghost
...