---
- name: Create Jellyfin media directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop: '{{ jellyfin_media_dirs }}'

- name: Config Jellyfin on Production
  block:
  - name: Get render group
    ansible.builtin.getent:
      database: group
      key: "{{ item }}"
      split: ':'
    register: getent_output
    loop:
      - render
      - video

  - ansible.builtin.debug:
      msg: "{{ getent_output.results[0].ansible_facts.getent_group.render[1] }}"

  - ansible.builtin.debug:
      msg: "{{ getent_output.results[1].ansible_facts.getent_group.video[1] }}"

  - name: Pull and run Jellyfin Docker image
    community.docker.docker_container:
      name: jellyfin
      image: "jellyfin/jellyfin:10.10.7"
      state: started
      restart_policy: "unless-stopped"
      network_mode: host
      recreate: true
      user: 0:0
      memory: "8G"
      volumes:
        - /srv/jellyfin/config:/config
        - /srv/jellyfin/cache:/cache
        - /mnt/media/Jellyfin:/media
      groups:
        - "{{ getent_output.results[0].ansible_facts.getent_group.render[1] }}"
        - "{{ getent_output.results[1].ansible_facts.getent_group.video[1] }}"
      devices:
        - /dev/dri/renderD128:/dev/dri/renderD128
        - /dev/kfd:/dev/kfd
      env:
        ROC_ENABLE_PRE_VEGA: "1"

  when: inventory_hostname != "default"

- name: Config Jellyfin on Staging
  block:
  - name: Pull and run Jellyfin Docker image
    community.docker.docker_container:
      name: jellyfin
      image: "jellyfin/jellyfin:10.10.7"
      state: started
      restart_policy: "unless-stopped"
      network_mode: host
      recreate: true
      volumes:
        - /srv/jellyfin/config:/config
        - /srv/jellyfin/cache:/cache
        - /mnt/media/Jellyfin:/media
  when: inventory_hostname == "default"

- name: Open jellyfin port on firewall
  become: true
  ansible.posix.firewalld:
    port: 8096/tcp
    permanent: true
    state: enabled
    immediate: true
...