---
- name: Delete backgrounds jump dir
  ansible.builtin.file:
    state: absent
    path: /mnt/media/Jump/backgrounds

- name: Create Jump directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop: '{{ jump_media_dirs }}'

- name: Copy icons and configurations
  ansible.builtin.copy:
    src: "{{ item.source }}"
    dest: "{{ item.destination }}"
  loop:
    - { source: 'jump/icon.png', destination: '/mnt/media/Jump/favicon/' }
    - { source: 'jump/sites.json', destination: '/mnt/media/Jump/sites/' }
    - { source: 'jump/favicon/', destination: '/mnt/media/Jump/sites/icons/' }
    - { source: 'jump/backgrounds', destination: '/mnt/media/Jump/' }

- name: Pull and run Jump dashboard Docker image
  community.docker.docker_container:
    name: jump
    image: "daledavies/jump:latest"
    state: started
    restart_policy: "unless-stopped"
    recreate: true
    volumes:
      - /mnt/media/Jump/backgrounds:/backgrounds
      - /mnt/media/Jump/favicon:/favicon
      - /mnt/media/Jump/sites:/sites
      - /mnt/media/Jump/search/search
    env:
      SITENAME: '{{ jump_site_name }}'
    ports:
      - 8123:8080
...