---
- name: Create Kavita media directories
  ansible.builtin.file:
    path: /mnt/media-nvm/Kavita
    state: directory
    mode: '0755'
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'

- name: Upload Kavita cron script
  ansible.posix.synchronize:
    src: kavita/new_file_uploaded.sh
    dest: /mnt/media-nvm/Kavita/

- name: Create cronjob that every 5 minutes creates dirs for newly added pdf books
  ansible.builtin.cron:
    name: "Check for pdf & epub files"
    state: present
    minute: "*/5"
    job: "/bin/bash /mnt/media-nvm/Kavita/new_file_uploaded.sh"

- name: Pull and run Kavita Docker image
  community.docker.docker_container:
    name: kavita
    image: "jvmilazz0/kavita:0.8.6"
    state: started
    recreate: true
    restart_policy: "unless-stopped"
    ports:
      - 5000:5000
    volumes:
      - /mnt/media-nvm/Kavita/config:/kavita/config
      - /mnt/media-nvm/Kavita/manga:/manga

...