---
- name: Create Kavita media directories
  ansible.builtin.file:
    path: /mnt/media/Kavita
    state: directory
    mode: '0755'

- name: Pull and run Kavita Docker image
  community.docker.docker_container:
    name: kavita
    image: "jvmilazz0/kavita:0.7.14"
    state: started
    recreate: true
    restart_policy: "unless-stopped"
    ports:
      - 5000:5000
    volumes:
      - /kavita/data/directory:/kavita/config
      - /mnt/media/Kavita:/manga

...