---
- name: Create LocalAI media directories
  ansible.builtin.file:
    path: '/mnt/media-nvm/LocalAI'
    state: directory
    mode: '0755'

- name: Pull and run LocalAI Docker image
  community.docker.docker_container:
    name: localai
    image: "localai/localai:v2.29.0"
    state: started
    restart_policy: "unless-stopped"
    recreate: true
    memory: "8G"
    cpus: "4"
    ports:
      - 8081:8080
    volumes:
      - /mnt/media-nvm/LocalAI:/build/models
    env:
      API_KEY: "{{ localai_api_key }}"

...