---
- name: Create Lychee media directories
  ansible.builtin.file:
    path: /mnt/media-nvm/Lychee
    state: directory
    mode: '0755'
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'

- name: Pull and run Lychee Docker image
  community.docker.docker_container:
    name: lychee
    image: "lycheeorg/lychee:v6.6.5"
    state: started
    recreate: true
    restart_policy: "unless-stopped"
    labels:
      sablier.enable: "true"
      sablier.group: "lychee"
    env:
      APP_URL: "http://192.168.100.45:8001"
    networks:
      - name: sleepers
    volumes:
      - /mnt/media-nvm/Lychee/conf:/conf
      - /mnt/media-nvm/Lychee/uploads:/uploads
      - /mnt/media-nvm/Lychee/sym:/sym