---
- name: Pull and run Navidrome
  community.docker.docker_container:
    name: navidrome
    image: "deluan/navidrome:0.53.3"
    state: started
    recreate: true
    restart_policy: "unless-stopped"
    ports:
      - 4533:4533
    volumes:
      - /mnt/media-nvm/Navidrome/music:/music
      - /mnt/media-nvm/Navidrome/data:/data
...