- name: Download node exporter archive (async)
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-1.8.2.linux-amd64.tar.gz"
    mode: '0644'
  async: 300
  poll: 0
  register: node_exporter_async

- name: Add node_exporter user
  become: true
  ansible.builtin.user:
    name: '{{ node_exporter_user }}'
    shell: /bin/false
    state: present
    create_home: false

- name: Copy Node Exporter service file
  become: true
  ansible.builtin.copy:
    src: files/node_exporter/node_exporter.service
    dest: /etc/systemd/system/

- name: Wait for Node Exporter archive download to complete
  ansible.builtin.async_status:
    jid: "{{ node_exporter_async.ansible_job_id }}"
  register: node_exporter_async_status
  until: node_exporter_async_status.finished
  retries: 100
  delay: 5

- name: Copy node exporter executable
  become: true
  ansible.builtin.copy:
    src: /tmp/node_exporter-1.8.2.linux-amd64/node_exporter
    dest: /usr/local/bin/
    group: '{{ node_exporter_user }}'
    owner: '{{ node_exporter_user }}'
    remote_src: true
    mode: preserve

- name: Reload systemctl daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: node_exporter
    state: restarted
    enabled: true