---
- name: Create ntfy directory
  ansible.builtin.file:
    path: /etc/ntfy
    state: directory
    owner: root
    group: root

- name: Copy ntfy Configurations
  become: true
  ansible.builtin.copy:
    src: ntfy/server.yml
    dest: /etc/ntfy/server.yml

- name: Pull and run ntfy server
  community.docker.docker_container:
    name: ntfy_server
    image: "binwiederhier/ntfy:v2.14.0"
    state: started
    restart_policy: "unless-stopped"
    volumes:
      - /etc/ntfy:/etc/ntfy
      - /var/lib/ntfy:/var/lib/ntfy
    command: serve
    ports:
      - 8008:80

- name: Add ntfy admin user and password vars
  ansible.builtin.lineinfile:
    path: '/etc/environment'
    state: present
    line: "{{ item }}"
  loop: "{{ ntfy_env_variables }}"
  no_log: true

- name: Create ntfy admin user
  ansible.builtin.expect:
    command: 'docker exec -it ntfy_server ntfy user add --role=admin {{ ntfy_admin }}'
    responses:
      (password*|confirm*): '{{ ntfy_password }}'
  register: admin_creation_status
  changed_when: admin_creation_status.rc == 0
  failed_when: admin_creation_status.rc != 1 and admin_creation_status.rc != 0

...