---
- name: Create Ollama media directories
  ansible.builtin.file:
    path: /mnt/media-nvm/Ollama
    state: directory
    mode: '0755'
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'

- name: Copy Ollama Dockerfile and entrypoint
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /mnt/media-nvm/Ollama
    mode: preserve
  loop:
    - 'ollama/Dockerfile'

- name: Build Ollama image with models
  community.docker.docker_image:
    name: "ollama/ollama-packituz"
    tag: "0.9.0-rc0-rocm"
    build:
      path: /mnt/media-nvm/Ollama
    source: build
    force_source: true

- name: Pull and run Ollama Docker image
  community.docker.docker_container:
    name: ollama
    image: "ollama/ollama-packituz:0.9.0-rc0-rocm"
    state: started
    recreate: true
    memory: "8G"
    cpus: "4"
    restart_policy: "unless-stopped"
    labels:
      sablier.enable: "true"
      sablier.group: "ollama"
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    networks:
      - name: sleepers
    volumes:
      - /mnt/media-nvm/Ollama:/root/.ollama

- name: Pull and run OpenwebUI
  community.docker.docker_container:
    name: openwebui
    image: "ghcr.io/open-webui/open-webui:v0.6.14"
    state: started
    recreate: true
    restart_policy: "unless-stopped"
    labels:
      sablier.enable: "true"
      sablier.group: "ollama"
    env:
      OLLAMA_BASE_URL: http://ollama:11434
    networks:
      - name: sleepers
    volumes:
      - /mnt/media-nvm/OpenWebUI:/app/backend/data


...