---
- name: Pull and run Omni-Tools Docker image
  community.docker.docker_container:
    name: omnitools
    image: "iib0011/omni-tools:0.6.0"
    state: started
    recreate: true
    restart_policy: "unless-stopped"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://0.0.0.0:80/" ]
    labels:
      sablier.enable: "true"
      sablier.group: "omnitools"
    networks:
      - name: sleepers
...