---
- name: Install the "Server with GUI" group
  ansible.builtin.dnf:
    name: "@Server with GUI"
    state: present

- name: Ensure Firewalld is active
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

- name: Set GUI to autostart
  ansible.builtin.command:
    cmd: systemctl set-default graphical.target
  register: target
  changed_when: target.stderr != ""

- name: Reboot
  become: true
  ansible.builtin.reboot:

- name: Remove podman & buildah
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: absent
  loop: '{{ packages_to_remove }}'

- name: Add Docker repo
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install docker
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: present
  loop: '{{ docker_packages }}'

- name: Install pip
  ansible.builtin.dnf:
    name: python3-pip
    state: present

- name: Enable docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Add admin user to docker group
  ansible.builtin.user:
    name: '{{ superuser_name }}'
    state: present
    shell: /bin/bash
    groups: docker
    append: yes

- name: Upgrade pip
  pip:
    name: pip
    state: latest

- name: Install epel key
  ansible.builtin.rpm_key:
    key: 'https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9'
    state: present

- name: Install borg
  ansible.builtin.dnf:
    name: borgbackup
    state: present

#- name: Install python docker
#  ansible.builtin.pip:
#    name: '{{ item }}'
#  loop:
#    - docker
#    - docker-compose
...