---
- name: Pull and run Pingvin-share
  community.docker.docker_container:
    name: pingvin
    image: "stonith404/pingvin-share:v0.22.2"
    state: started
    restart_policy: "unless-stopped"
    recreate: true
    ports:
      - 3001:3000
    volumes:
      - /mnt/media/Pingvin/data:/opt/app/backend/data
      - /mnt/media/Pingvin/data/images:/opt/app/frontend/public/img

...