---
- name: Pull and run Portainer Docker image
  community.docker.docker_container:
    name: portainer
    image: "portainer/portainer-ce:latest"
    state: started
    restart_policy: "always"
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /media/Portainer:/data
...