---
- name: Create Romm directories
  ansible.builtin.file:
    path: /mnt/media/Romm
    state: directory
    mode: '0755'
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'

- name: Create app.env file
  ansible.builtin.copy:
    dest: /mnt/media/Romm/app.env
    content: |
      DB_HOST=romm-db
      DB_NAME=romm
      DB_USER=romm-user
      DB_PASSWD={{ romm_db_password }}
      IGDB_CLIENT_ID={{ romm_igdb_client_id }}
      IGDB_CLIENT_SECRET={{ romm_igdb_client_secret }}
      ROMM_AUTH_SECRET_KEY={{ romm_auth_secret_key }}
      ROMM_AUTH_USERNAME={{ romm_auth_username }}
      ROMM_AUTH_PASSWORD={{ romm_auth_password }}

- name: Create db.env fiel
  ansible.builtin.copy:
    dest: /mnt/media/Romm/db.env
    content: |
      MYSQL_ROOT_PASSWORD={{ romm_db_root_password }}
      MYSQL_DATABASE=romm
      MYSQL_USER=romm-user
      MYSQL_PASSWORD={{ romm_db_password }}

- name: Copy Docker-compose file
  become: false
  ansible.posix.synchronize:
    src: files/romm/docker-compose.yml
    dest: /mnt/media/Romm

- name: Run Romm
  community.docker.docker_compose_v2:
    project_src: /mnt/media/Romm

...