---
- name: Create Caddy directories
  ansible.builtin.file:
    path: /mnt/media-nvm/Caddy
    state: directory
    mode: '0755'
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'

- name: Copy Caddy Dockerfile
  ansible.posix.synchronize:
    src: 'caddy/Dockerfile'
    dest: /mnt/media-nvm/Caddy
  register: caddy_dockerfile_sync

- name: Build Caddy image with sablier plugin
  community.docker.docker_image:
    name: "caddy-packituz"
    tag: "latest-with-sablier"
    build:
      path: /mnt/media-nvm/Caddy
    source: build
    force_source: true
  when: caddy_dockerfile_sync is changed

- name: Setup Caddy file
  ansible.posix.synchronize:
    src: 'caddy/Caddyfile'
    dest: '/mnt/media-nvm/Caddy/Caddyfile'

- name: Pull and run Caddy Docker image
  community.docker.docker_container:
    name: caddy
    image: "caddy-packituz:latest-with-sablier"
    state: started
    restart_policy: "unless-stopped"
    recreate: true
    ports:
      - "3003:3003"
      - "8001:8001"
      - "8888:8888"
      - "3002:3002"
      - "8889:8889"
      - "8887:8887"
      - "8886:8886"
      - "8885:8885"
    volumes:
      - '/mnt/media-nvm/Caddy/Caddyfile:/etc/caddy/Caddyfile:ro'
    networks:
      - name: sleepers

- name: Pull and run Sablier Docker image
  community.docker.docker_container:
    name: sablier
    image: "sablierapp/sablier:1.10.1"
    state: started
    restart_policy: "unless-stopped"
    recreate: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - name: sleepers
...