---
- name: Pull and run Jump dashboard Docker image
  community.docker.docker_container:
    name: sablier
    image: "sablierapp/sablier:1.9.0"
    state: started
    restart_policy: "unless-stopped"
    recreate: true
    command:
      - start
      - --provider.name=docker
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
...