---
- name: Create Caddy directories
  ansible.builtin.file:
    path: /mnt/media-nvm/Caddy
    state: directory
    mode: '0755'
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'

- name: Copy Caddy Dockerfile
  ansible.posix.synchronize:
    src: 'caddy/Dockerfile'
    dest: /mnt/media-nvm/Caddy

- name: Build Caddy image with sablier plugin
  community.docker.docker_image:
    name: "caddy-packituz"
    tag: "2.10.0-with-sablier"
    build:
      path: /mnt/media-nvm/Caddy
    source: build
    force_source: true

- name: Setup Caddy file
  ansible.posix.synchronize:
    src: 'caddy/Caddyfile'
    dest: '/mnt/media-nvm/Caddy/Caddyfile'

- name: Pull and run Caddy Docker image
  community.docker.docker_container:
    name: caddy
    image: "caddy-packituz:2.10.0-with-sablier"
    state: started
    restart_policy: "unless-stopped"
    recreate: true
    ports:
      - "3003:3003"
      - "8001:8001"
      - "8888:8888"
      - "3002:3002"
    volumes:
      - '/mnt/media-nvm/Caddy/Caddyfile:/etc/caddy/Caddyfile:ro'
    networks:
      - name: sleepers

- name: Pull and run Sablier Docker image
  community.docker.docker_container:
    name: sablier
    image: "sablierapp/sablier:1.9.0"
    state: started
    restart_policy: "unless-stopped"
    recreate: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - name: sleepers
...