repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=45000' ]
      - id: no-commit-to-branch
        args: [ '--branch', 'master' ]