[project]
name = "home-server"
version = "0.1.0"
description = "Home Server setup with tools like jellyfin, kavita, navidrome, etc."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible==14.3.1",
    "molecule==26.8.0",
    "molecule-plugins[vagrant]==26.7.15",
    "python-vagrant==1.0.0",
]

[dependency-groups]
dev = [
    "commitizen>=4.9.1",
    "pre-commit>=4.3.0",
]
