services:
  kasm:
    image: lscr.io/linuxserver/kasm:1.120.20221218
    container_name: kasm
    privileged: true
    security_opt:
      - apparmor:rootlesskit
    environment:
      - KASM_PORT=443
    volumes:
      - /mnt/media-nvm/Kasm/data:/opt
      - /mnt/media-nvm/Kasm/profiles:/profiles
      - /dev/input:/dev/input
      - /run/udev/data:/run/udev/data
    ports:
      - 3004:3000
      - 443:443
    restart: unless-stopped