
Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2004"

    config.vm.provider "virtualbox" do |vbox|
        vbox.customize ["modifyvm", :id, "--vram", "128"]
        vbox.customize ["modifyvm", :id, "--accelerate3d", "on"]
        vbox.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
        vbox.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
    end

    config.vm.provider "libvirt" do |libvirt|
        libvirt.memory = 4096
        libvirt.graphics_type = "vnc"
        libvirt.video_type = "virtio"
        libvirt.video_vram = 262144
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbooks/main.yml"
    end


end
