---
- name: Create Omnitools media directories
  ansible.builtin.file:
    path: /mnt/media-nvm/Omnitools
    state: directory
    mode: '0755'
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'

- name: Copy Docker-compose file
  ansible.posix.synchronize:
    src: files/utils/omnitools/docker-compose.yml
    dest: /mnt/media-nvm/Omnitools

- name: Run Omnitools
  community.docker.docker_compose_v2:
    project_src: /mnt/media-nvm/Omnitools
...