---
- name: Create DocuSeal media directories
  ansible.builtin.file:
    path: /mnt/media-nvm/Docuseal/data
    state: directory
    mode: '0755'
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'

- name: Copy Docker-compose file
  ansible.posix.synchronize:
    src: files/utils/docuseal/docker-compose.yml
    dest: /mnt/media-nvm/Docuseal

- name: Run DocuSeal
  community.docker.docker_compose_v2:
    project_src: /mnt/media-nvm/Docuseal

...