---
- name: Create Stirling PDF directories
  ansible.builtin.file:
    path: /mnt/media-nvm/StirlingPDF/
    state: directory
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'
    mode: '0755'

- name: Copy Docker-compose file
  ansible.posix.synchronize:
    src: files/utils/stirlingpdf/docker-compose.yml
    dest: /mnt/media-nvm/StirlingPDF

- name: Run Stirlingpdf
  community.docker.docker_compose_v2:
    project_src: /mnt/media-nvm/StirlingPDF

...