version: "3.8"
services:
  lychee:
    image: "lycheeorg/lychee:v7.5.4"
    container_name: "lychee"
    restart: unless-stopped
    labels:
      sablier.enable: "true"
      sablier.group: "lychee"
    environment:
      APP_URL: "https://photos.packituz.dev"
      DB_CONNECTION: sqlite
    networks:
      - sleepers
    volumes:
#      - /mnt/media-nvm/Lychee/conf:/conf
      - /mnt/media-nvm/Lychee/uploads:/app/public/uploads
      - /mnt/media-nvm/Lychee/storage/app:/app/storage/app
      - /mnt/media-nvm/Lychee/logs:/app/storage/logs
      - /mnt/media-nvm/Lychee/tmp:/app/storage/tmp
      - /mnt/media-nvm/Lychee/conf/.env:/app/.env

networks:
  sleepers:
    external: true