---
- name: Install EPEL repository release
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Install Monit package
  ansible.builtin.dnf:
    name: monit
    state: present
    update_cache: true

- name: Delete previous monit rc files
  ansible.builtin.file:
    state: absent
    path: '/etc/monit.d/'

- name: Upload monit configuration
  ansible.builtin.copy:
    src: '{{ item.source }}'
    dest: '{{ item.destination }}'
  loop:
    - { source: 'monit/monitrc', destination: '/etc/monitrc' }
    - { source: 'monit/monit_rc_files/', destination: '/etc/monit.d/' }

- name: Copy scripts
  ansible.builtin.copy:
    src: 'monit/scripts'
    dest: '/etc/monit.d/'
    mode: preserve

- name: Configure monitrc
  ansible.builtin.blockinfile:
    path: '/etc/monitrc'
    block: |
      set httpd port 2812 and
        allow 0.0.0.0/0
        allow {{ monit_admin }}:{{ monit_password }}
    validate: monit -t %s

- name: Reload monit
  ansible.builtin.command:
    cmd: monit reload

- name: Open monit port on firewall
  ansible.posix.firewalld:
    port: 2812/tcp
    permanent: true
    state: enabled
    immediate: true

- name: Enable monit service
  ansible.builtin.systemd:
    name: monit
    state: started
    enabled: true
...