---
- name: Create Lychee media directories
  ansible.builtin.file:
    path: /mnt/media-nvm/Lychee
    state: directory
    mode: '0755'
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'

- name: Copy Docker-compose file
  ansible.posix.synchronize:
    src: files/media/lychee/docker-compose.yml
    dest: /mnt/media-nvm/Lychee

- name: Run Lychee
  community.docker.docker_compose_v2:
    project_src: /mnt/media-nvm/Lychee