mqtt:
  enabled: False

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: true
  mode: continuous

live:
  quality: 8

record:
  enabled: true
  retain:
    days: 10
    mode: motion
  events:
    retain:
      mode: motion
      default: 10
    pre_capture: 20
    post_capture: 15

go2rtc:
  streams:
    depas:
      - "rtsp://{{ frigate_depas_user }}:{{ frigate_depas_password }}@192.168.100.89:554/stream1" # <----- The stream you want to use for detection
      - "ffmpeg:depas#audio=aac"
    depas_roof_garden:
      - "rtsp://{{ frigate_depas_user }}:{{ frigate_depas_password }}@192.168.100.92:554/stream1" # <----- The stream you want to use for detection
      - "ffmpeg:depas#audio=aac"

cameras:
  depas:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/depas
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    snapshots:
      enabled: true
    detect:
      enabled: true
      fps: 8
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution

  depas_roof_garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/depas_roof_garden
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    snapshots:
      enabled: true
    detect:
      enabled: true
      fps: 5
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution