authRequireGuestsToLogin: true

pageTitle: Home-Server

accessControlLists:
  - name: "admins"
    permissions:
      view: true
      exec: true
      logs: true
    matchUsergroups:
      - "admins"
    addToEveryAction: true

authLocalUsers:
  enabled: true
  users:
    - username: ${{ ADMIN_USER }}
      usergroup: admins
      password: ${{ ADMIN_PASSWORD }}

actions:
  # Host Machine Controls
  - title: "Reboot Host Machine"
    icon: "🔄"
    shell: "nsenter -t 1 --all --root=/host systemctl reboot"
    arguments:
      - type: confirmation
        title: 'Reboot?'
    timeout: 10

  - title: "Shutdown Host Machine"
    icon: "🛑"
    shell: "nsenter -t 1 --all --root=/host systemctl poweroff"
    arguments:
      - type: confirmation
        title: 'Reboot?'
    timeout: 10

  - title: "Restart container service"
    icon: "🔄"
    shell: "docker restart {{ container }}"
    maxConcurrent: 1
    arguments:
      - name: container
        description: Container service to restart
        choices:
          - title: Jellyfin (TV Server)
            value: jellyfin
          - title: Navidrome (Music)
            value: navidrome
          - title: Kavita (Books)
            value: kavita
          - title: Audiobooks (AudioBooks)
            value: Audiobooks
          - title: Grafana (Monitoring)
            value: grafana
          - title: Joplin (Notes)
            value: joplin-app
          - title: PaperlessNGX (Documents)
            value: paperlessngx-webserver
          - title: Lubelogger (Cars)
            value: lubelogger
          - title: Docuseal (Document Signing)
            value: docuseal
          - title: Romm (VideoGames)
            value: romm-app
          - title: Transmission (Seedbox)
            value: transmission
          - title: Immich (Photos)
            value: immich_server
          - title: Floci (AWS)
            value: floci
          - title: OliveTin (UI Administrator)
            value: olivetin
          - title: Jump (Home Dashboard)
            value: jump

  - title: Update System
    shell: "nsenter -t 1 --all --root=/host env DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket dnf upgrade --refresh --setopt=diskspacecheck=0 -y"
    timeout: 3600

  - title: Clean System Cache
    shell: "dnf clean all"
    timeout: 300

  - title: Clean Docker Images
    shell: "docker image prune --all -f"
    timeout: 300

  # Install stuff for borgbackup
  - title: Install borgbackup
    shell: "microdnf install borgbackup -y"
    timeout: 60

#  K3s Server Actions
  - title: Shutdown Cluster
    shell: |
      TOKEN=${{ OLIVETIN_K3S_TOKEN }}
      # Node 1
      echo "Shutting down Node 1"
      curl -sS -X POST -H "X-Authorization-Token: ${TOKEN}" http://192.168.3.5:9000/hooks/trigger-cluster-shutdown >/dev/null
      # Master
      echo "Shutting down Master Node"
      curl -sS -X POST -H "X-Authorization-Token: ${TOKEN}" http://192.168.3.6:9000/hooks/trigger-cluster-shutdown >/dev/null
    arguments:
      - type: confirmation
        title: 'Shutdown K3s Cluster?'
    timeout: 60

dashboards:
  - title: Home-Server
    contents:
      - title: "Reboot Host Machine"
      - title: "Shutdown Host Machine"
      - title: "Restart container service"
      - title: "Update System"
      - title: "Clean System Cache"
      - title: "Clean Docker Images"
      - title: "Install borgbackup"
  - title: K3s Remote Server
    contents:
      - title: "Shutdown Cluster"