---
- name: Install olivetin
  ansible.builtin.dnf:
    name: 'https://github.com/OliveTin/OliveTin/releases/download/3000.19.0/OliveTin_linux_amd64.rpm'
    state: present
    disable_gpg_check: true

- name: Copy config
  ansible.builtin.copy:
    src: files/base/olivetin/config.yaml
    dest: /etc/OliveTin/
    mode: preserve

- name: Create .env file
  ansible.builtin.copy:
    dest: /etc/olivetin.env
    owner: root
    group: root
    mode: '0644'
    content: |
      ADMIN_PASSWORD='{{ olivetin_admin_password }}'
      ADMIN_USER='{{ olivetin_admin_user }}'
      OLIVETIN_K3S_TOKEN='{{ olivetin_k3s_token }}'
      OLIVETIN_BORGBASE_PASSPHRASE='{{ olivetin_borgbase_passphrase }}'
      OLIVETIN_BORGBASE_IMMICH_REPO='{{ olivetin_borgbase_immich_repo }}'
      OLIVETIN_BORGBASE_KAVITA_REPO='{{ olivetin_borgbase_kavita_repo }}'

- name: Create OliveTin Systemd Directory
  ansible.builtin.file:
    state: directory
    path: '/etc/systemd/system/OliveTin.service.d/'
      
- name: Override Systemd OliveTin configuration
  ansible.builtin.copy:
    dest: /etc/systemd/system/OliveTin.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      [Service]
      EnvironmentFile=/etc/olivetin.env

- name: Open oliveTin por on firewall
  ansible.posix.firewalld:
    port: 1337/tcp
    permanent: true
    state: enabled
    immediate: true

- name: Enabled oliveTin service
  ansible.builtin.systemd:
    name: OliveTin
    state: restarted
    enabled: true
    daemon_reload: true
...