global:
  scrape_interval: 10s

rule_files:
#  - "rules.yml"

alerting:
  alertmanagers:
    - static_configs:
      - targets:
#          - localhost:9093

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: [ "localhost:9100" ]

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'folder_size'
    static_configs:
      - targets: ['localhost:9974']

  - job_name: 'docker'
    static_configs:
      - targets: ['127.0.0.1:8080']

  - job_name: 'dirsize'
    static_configs:
      - targets: ['127.0.0.1:8000']


