global:
  scrape_interval: 10s

rule_files:
#  - "rules.yml"

alerting:
  alertmanagers:
    - static_configs:
      - targets:
#          - localhost:9093

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: [ "localhost:9100" ]

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    basic_auth:
      username: '{{ prometheus_admin_user }}'
      password: '{{ prometheus_admin_password_plain }}'


