version: "3"
services:
  romm:
    image: rommapp/romm:3.10.2
    container_name: romm
    volumes:
      - /mnt/media-nvm/Romm/resources:/romm/resources
      - /mnt/media-nvm/Romm/redis-data:/redis-data
      - /mnt/media-nvm/Romm/library:/romm/library
      - /mnt/media-nvm/Romm/assets:/romm/assets
      - /mnt/media-nvm/Romm/config:/romm/config
      - /mnt/media-nvm/Romm/logs:/romm/logs
    depends_on:
      - romm-db
    labels:
      sablier.enable: true
      sablier.group: "romm"
    restart: "unless-stopped"
    networks:
      - sleepers
    env_file:
      - /mnt/media-nvm/Romm/app.env

  romm-db:
    image: mariadb:lts-jammy
    container_name: romm-db
    restart: "unless-stopped"
    labels:
      sablier.enable: true
      sablier.group: "romm"
    networks:
      - sleepers
    env_file:
      - /mnt/media-nvm/Romm/db.env
    volumes:
      - /mnt/media-nvm/Romm/db:/var/lib/mysql

networks:
  sleepers:
    external: true