- name: Create Blackbox directories
  ansible.builtin.file:
    path: /mnt/media-nvm/Blackbox/
    state: directory
    mode: '0755'
    owner: '{{ superuser_name }}'
    group: '{{ superuser_name }}'

# Use sync
- name: Copy Blackbox configuration file
  ansible.posix.synchronize:
    src: monitoring/prometheus/exporters/blackbox/blackbox.yml
    dest: /mnt/media-nvm/Blackbox/

- name: Pull and run Blackbox Exporter
  community.docker.docker_container:
    name: blackbox-exporter
    image: quay.io/prometheus/blackbox-exporter:v0.25.0
    recreate: true
    restart_policy: "unless-stopped"
    ports:
      - 9115:9115
    volumes:
      - /mnt/media-nvm/Blackbox/:/config
    command: --config.file=/config/blackbox.yml
