services:
  paperlessngx-broker:
    image: docker.io/library/redis:8
    container_name: paperlessngx-broker
    restart: unless-stopped
    labels:
      sablier.enable: true
      sablier.group: "paperlessngx"
    networks:
      - sleepers
    volumes:
      - /mnt/media-nvm/PaperlessNGX/redisdata:/data
      
  paperlessngx-webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperlessngx-webserver
    restart: unless-stopped
    labels:
      sablier.enable: true
      sablier.group: "paperlessngx"
    depends_on:
      - paperlessngx-broker
    volumes:
      - /mnt/media-nvm/PaperlessNGX/data:/usr/src/paperless/data
      - /mnt/media-nvm/PaperlessNGX/media:/usr/src/paperless/media
      - /mnt/media-nvm/PaperlessNGX/export:/usr/src/paperless/export
      - /mnt/media-nvm/PaperlessNGX/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    networks:
      - sleepers
    environment:
      - PAPERLESS_REDIS=redis://paperlessngx-broker:6379
      - USERMAP_UID=1000
      - USERMAP_GID=1000
      - PAPERLESS_OCR_LANGUAGE=spa
      - PAPERLESS_URL=https://papers.packituz.dev


networks:
  sleepers:
    external: true