version: '3'
services:

  app:
    image: ghost:5
    cap_add:
      - CAP_SYS_NICE
    security_opt:
      - seccomp:unconfined
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - db
    env_file:
      - /mnt/media/Ghost/app.env
    volumes:
      - /mnt/media/Ghost/content:/var/lib/ghost/content
  db:
    image: mysql:9
    security_opt:
      - seccomp:unconfined
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - /mnt/media/Ghost/db.env
    volumes:
      - /mnt/media/Ghost/mysql:/var/lib/mysql