---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: almalinux
    box: almalinux/9
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
  ansible_args:
    - --ask-vault-pass
verifier:
  name: ansible
