# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "almalinux/9"

  config.vm.network "private_network", ip: "192.168.56.2"


  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "configure_server.yml"
  end

end
