name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy-playbooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Install requirements.txt
        run: pip install -r requirements/requirements.txt

      - name: Install ansible requirements.yml
        run: ansible-galaxy install -r playbooks/requirements.yml

      - name: Create vault pass file
        run: echo ${{ secrets.ANSIBLE_VAULT_PASSWORD }} > .vault_pass.txt

      - name: Create deployment inventory file
        run: echo ${{ secrets.SERVER_SSH_ADDRESS }} > playbooks/inventor.ini

      - name: Download cloudflared
        run: wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared

      - name: Create ssh configuration
        run: |
          mkdir -p ~/.ssh/
          echo "Host ${{ secrets.SERVER_SSH_ADDRESS }}" > ~/.ssh/config
          echo 'ProxyCommand ~/cloudflared access ssh --hostname %h' >> ~/.ssh/config

      - name: Run playbooks
        run: /bin/bash scripts/make/run_deployment.sh '--tags jellyfin-setup'
