name: Deploy
on:
  push:
    branches:
      - master
    paths:
      - playbooks/**
      - uv.lock
      - pyproject.toml
      - .github/**

jobs:
  deploy-media:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags media-group'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

  deploy-jump:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags jump-setup'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

  deploy-utils:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags utils-group'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

  deploy-monit:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags monit-group'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}


  deploy-gaming:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags gaming-group'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}


  deploy-downloaders:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags downloaders-group'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

  deploy-ai:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags ai-group'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

  deploy-sablier:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags sablier-setup'
    if: ${{ always() }}
    needs: [ deploy-jump, deploy-media, deploy-utils, deploy-gaming, deploy-downloaders, deploy-ai ]
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

  deploy-cadvisor:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags cadvisor-setup'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

  deploy-foldersize:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags foldersize-setup'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

  deploy-blackbox:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags blackbox-setup'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

  deploy-node:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags node-setup'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

  deploy-pixai:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags pixai-setup'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

  deploy-monitoring:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags prometheus-setup'
    needs: [ deploy-cadvisor, deploy-foldersize, deploy-blackbox, deploy-node, deploy-pixai ]
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
