name: Deploy
on:
  push:
    branches:
      - master
    paths:
      - playbooks/**
      - uv.lock
      - pyproject.toml
      - .github/**

jobs:
  deploy-media:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags media-group'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

  deploy-jump:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags jump-setup'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

  deploy-utils:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags utils-group'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}


  deploy-monitoring:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags monitoring-group'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}


  deploy-monit:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags monit-group'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}


  deploy-gaming:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags gaming-group'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}


  deploy-downloaders:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags downloaders-group'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

  deploy-ai:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags ai-group'
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

  deploy-sablier:
    uses: ./.github/workflows/reusable-playbook-workflow.yaml
    with:
      playbook_params: '--tags sablier-setup'
    if: ${{ always() }}
    needs: [deploy-media, deploy-utils, deploy-gaming, deploy-downloaders, deploy-ai]
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SERVER_SSH_ADDRESS: ${{ secrets.SERVER_SSH_ADDRESS }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
